language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
 - sudo apt-get install -qq python-numpy python-scipy

# Install packages
install:
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:  
  - py.test tests/
