language: python
python:
  - "3.4"

# Setup anaconda
before_install:
# Install packages
  - PIP_ARGS="-I --trusted-host lovelace.cs.umn.edu --find-links=http://lovelace.cs.umn.edu/schaefer/wheelhouse/ --use-wheel --allow-external --allow-insecure"
  - pip install $PIP_ARGS -r requirements.txt
install:
  - python setup.py install

script:  
  - py.test tests/
