language: python
python:
  - "3.3"
  - "3.4"

# Setup anaconda
before_install:
# Install packages
  - pip install -r requirements.txt
install:
  - python setup.py install

script:  
  - py.test tests/
